# Generated by Django 6.0.2 on 2026-02-14 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('year_published', models.IntegerField(help_text='Year the book was published')),
                ('summary', models.TextField(help_text='Book summary and review')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book Review',
                'verbose_name_plural': 'Book Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiteracyAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_review', 'First Review'), ('five_books', '5 Books Read'), ('ten_books', '10 Books Read'), ('consistent_reader', 'Consistent Reader'), ('ambassador', 'Literacy Ambassador')], max_length=50)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literacy_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Literacy Achievement',
                'verbose_name_plural': 'Literacy Achievements',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='LiteracyLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('class', 'By Class'), ('grade', 'By Grade'), ('school', 'School-wide')], max_length=20)),
                ('scope_value', models.CharField(help_text="Class name, grade, or 'school'", max_length=100)),
                ('books_read', models.IntegerField(default=0)),
                ('consistency_score', models.IntegerField(default=0, help_text='Based on consistent submissions')),
                ('verified_reviews', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('is_monthly_ambassador', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_score', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='LiteracyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='literacy.bookreview')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literacy_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Literacy Post',
                'verbose_name_plural': 'Literacy Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiteracyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literacy_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='literacy.literacypost')),
            ],
            options={
                'verbose_name': 'Literacy Comment',
                'verbose_name_plural': 'Literacy Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['student', 'status'], name='literacy_bo_student_be88d6_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['status', 'created_at'], name='literacy_bo_status_21129e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='literacyachievement',
            unique_together={('student', 'achievement_type')},
        ),
        migrations.AddIndex(
            model_name='literacyleaderboard',
            index=models.Index(fields=['scope', 'scope_value', '-total_score'], name='literacy_li_scope_abfe1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='literacyleaderboard',
            unique_together={('student', 'scope', 'scope_value')},
        ),
        migrations.AddIndex(
            model_name='literacypost',
            index=models.Index(fields=['student', 'created_at'], name='literacy_li_student_cb81a2_idx'),
        ),
    ]
