# Generated by Django 6.0.2 on 2026-02-12 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('librarian', 'Librarian')], default='student', max_length=20)),
                ('nis', models.CharField(blank=True, help_text='Nomor Induk Siswa', max_length=20, null=True, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('L', 'Laki-laki (Male)'), ('P', 'Perempuan (Female)')], max_length=1, null=True)),
                ('kelas', models.CharField(blank=True, help_text='Kelas/Class', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
