# Generated by Django 6.0.2 on 2026-02-14 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('emoji', models.CharField(default='📖', help_text='Emoji representation', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name_plural': 'Attendance Activities',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('auto_checked_out', 'Auto Checked Out')], default='checked_in', max_length=20)),
                ('custom_activity', models.TextField(blank=True, help_text='Custom activity if not in predefined list')),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Visit duration in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('activities', models.ManyToManyField(blank=True, related_name='attendance_records', to='attendance.attendanceactivity')),
            ],
            options={
                'ordering': ['-check_in_time'],
                'indexes': [models.Index(fields=['user', 'check_in_time'], name='attendance__user_id_dbf2e9_idx'), models.Index(fields=['status', 'check_in_time'], name='attendance__status_094936_idx')],
            },
        ),
    ]
